### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#This will create this metric in all the tiers, under this path
#metricPrefix: Custom Metrics|Starter

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Custom Metrics|Extension Starter CI"

servers:
  - host: https://www.appdynamics.com/
    name: AppDynamics
    username: user
    password: welcome

  - host: https://www.yahoo.com/
    name: Yahoo
    username: user
    passwordEncrypted: C043Fag+LKEZM0AQTWPy2g==

# number of concurrent tasks
numberOfThreads: 1
encryptionKey: welcome

connection:
  socketTimeout: 2000
  connectTimeout: 2000
  sslCertCheckEnabled: false
  sslVerifyHostname: false
  sslProtocols: ["TLSv1"]

#proxy:
#  uri: http://localhost:9090
#  username: proxyyuser
#  password: proxypassword

#taskSchedule:
#  numberOfThreads: 1
#  taskDelaySeconds: 300

# below section shows how to configure metrics you want to pull and how to list metric's qualifiers

#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier
#   convert
#   delta
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

metrics:
  - CPUUtilization:
      alias: "Processor Utilization"
      aggregationType: "AVERAGE"
      timeRollUpType: "AVERAGE"
      clusterRollUpType: "INDIVIDUAL"
      multiplier: ""
      convert:
      delta:

metricPathReplacements:
  - replace: "Percent"
    replaceWith: "%"
  - replace: "OneMinuteRate"
    replaceWith: "1 min Rate"



# Generate a custom dashboard based on the provided template
customDashboard:
  enabled: false
  dashboardName: ""

  # Update the path to the dashboard file.
  pathToSIMDashboard: ""
  #pathToNormalDashboard: "monitors/SampleMonitor/normalDashboard.json"

controllerInfo:
  controllerHost: ""
  controllerPort: 8090
  account: ""
  username: ""
  password: ""
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""